### ISSUE TITLE
socket.io error connect  fair-value.js cannot read property of undefined 

### ISSUE THREAD

**Issue by amoscatelli1** [thrasher-/gocryptotrader#33]
What would be causing this:
13:14:45.664 main Requiring authentication to web client
13:14:45.707 main Listening to admins on port 3000
13:14:45.717 broker Exchange details { exchange: 'OkCoin',
  pair: 'BTC/USD',
  minTick: 0.01,
  minSize: 0.01,
  makeFee: 0.001,
  takeFee: 0.002,
  hasSelfTradePrevention: false }
13:14:45.731 main Unhandled rejection! TypeError: Cannot read property 'value' of undefined
    at new FairValueEngine (/opt/finbots/K/Krypto-trading-bot/app/server/fair-value.js:22:67)
    at Object.<anonymous> (/opt/finbots/K/Krypto-trading-bot/app/server/main.js:204:22)
    at next (native)
    at fulfilled (/opt/finbots/K/Krypto-trading-bot/app/server/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3 Promise {
  <rejected> TypeError: Cannot read property 'value' of undefined
    at new FairValueEngine (/opt/finbots/K/Krypto-trading-bot/app/server/fair-value.js:22:67)
    at Object.<anonymous> (/opt/finbots/K/Krypto-trading-bot/app/server/main.js:204:22)
    at next (native)
    at fulfilled (/opt/finbots/K/Krypto-trading-bot/app/server/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3 }
13:14:45.762 main Error THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END
13:14:47.462 okcoin Successfully connected to addChannel: ok_sub_spotusd_btc_depth_20
13:14:47.465 okcoin Successfully connected to addChannel: ok_sub_spotusd_btc_trades
13:14:47.467 okcoin Successfully connected to login
13:14:47.762 main Exit code 0
error: Forever detected script exited with code: 0
error: Script restart attempt #1
13:14:48.996 main Requiring authentication to web client
13:14:49.047 main Listening to admins on port 3000
13:14:49.067 broker Exchange details { exchange: 'OkCoin',

Thank you for your answer.

**Comment by amoscatelli1** [comment]
Sorry guys, this somehow ended in wrong repository
